/**
 * GuardRail x402 sell rail: agents sell their capabilities over x402/B402.
 *
 * This server is a framework-agnostic x402 merchant built on the Altana SDK's
 * createX402Merchant. Each GuardRail agent exposes a paid capability endpoint:
 *
 *   GET /v1/agents/health  -> health-guard report (paid)
 *   GET /v1/agents/yield   -> yield-router report (paid)
 *   GET /v1/agents/lp      -> lp-guardian report (paid)
 *   GET /v1/agents/grid    -> gridbot report (paid)
 *
 * Payment flow (x402 v2 / B402 wire):
 *   1. Buyer hits an endpoint with no X-PAYMENT -> merchant returns 402 with
 *      the challenge: price in $U, payTo = GuardRail agent wallet, accepted
 *      rails (EIP-3009 on $U, permit2-exact on USDT).
 *   2. Buyer (BNB Agent Studio `bag x402 buy`, Altana `fetchWithX402`, or any
 *      B402 client) signs an EIP-3009 TransferWithAuthorization for the exact
 *      amount and retries with X-PAYMENT.
 *   3. Merchant verifies the signature, settles onchain, serves the report.
 *
 * The settlement broadcasts from the facilitator key (the GuardRail admin
 * wallet), paying the guard gas. The money lands in payTo (same wallet).
 *
 * Usage: tsx src/x402-server.ts [--port 8787]
 */

import { createServer } from "node:http";
import { privateKeyToAccount } from "viem/accounts";
import { parseEther } from "viem";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { U_TOKEN, createX402Merchant } from "@altananetwork/x402-server";
import { BNB_TESTNET } from "@altananetwork/sdk";

const WALLET = "0xa847F3BBF69e8A888b59BC8729ce787E0dB5be97" as `0x${string}`;
const PRICE_U = parseEther("0.1"); // 0.1 $U per report

function loadAdminKey(): `0x${string}` {
  // Prefer an injected secret (Render env var / secret file); fall back to
  // the local state file for the on-VM demo. Env wins so a deploy doesn't
  // need to ship the gitignored .guardrail-state.json.
  if (process.env.GUARDRAIL_ADMIN_KEY) {
    return process.env.GUARDRAIL_ADMIN_KEY as `0x${string}`;
  }
  const f = join(process.cwd(), ".guardrail-state.json");
  if (!existsSync(f)) throw new Error("no .guardrail-state.json (set GUARDRAIL_ADMIN_KEY)");
  return JSON.parse(readFileSync(f, "utf8")).adminKey as `0x${string}`;
}

// On testnet only the EIP-3009 rail on $U can actually settle: the permit2
// rail's default asset (mainnet BSC-USDT) does not exist on chain 97, so
// offering it would always revert at settlement. Keep the merchant honest:
// one rail per chain, the one that works.
const merchant = createX402Merchant({
  chainId: BNB_TESTNET.chainId,
  payTo: WALLET,
  price: PRICE_U,
  minPrice: parseEther("0.01"),
  maxPrice: parseEther("1"),
  rails: [{ rail: "eip3009", token: U_TOKEN[97] }],
  description: "GuardRail agent capability report (health / yield / LP / grid)",
  resource: { url: "https://guardrail.local/v1/agents", mimeType: "application/json" },
  facilitator: privateKeyToAccount(loadAdminKey()),
  rpcUrl: BNB_TESTNET.publicRpcUrl,
  chain: BNB_TESTNET.chain,
});

const PORT = Number(process.argv.find((a) => a.startsWith("--port"))?.split("=")[1] ?? 8787);

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "content-type": "application/json", "access-control-allow-origin": "*" },
  });
}

/** The paid capability: the live agent report. In a real deployment each
 *  agent computes its report on demand; here we run the one-shot check and
 *  return its output as the deliverable. */
async function agentReport(kind: string): Promise<string> {
  const script =
    kind === "health"
      ? "src/agents/health-guard.ts"
      : kind === "yield"
        ? "src/agents/yield-router.ts"
        : kind === "lp"
          ? "src/agents/lp-guardian.ts"
          : "src/agents/gridbot.ts";
  // NOTE: the report is generated by the agent binary (tsx child process).
  // For the hackathon demo the server returns a live report by running the
  // agent's read loop once; the paid response embeds that output.
  const { execFileSync } = await import("node:child_process");
  try {
    // Use the local tsx binary directly (npx re-resolution from inside a tsx
    // process is slow and can exceed a 60s timeout) and give it headroom.
    const tsxBin = join(process.cwd(), "node_modules", ".bin", "tsx");
    const out = execFileSync(tsxBin, [script, "--once"], {
      cwd: process.cwd(), // demo dir: scripts live at src/agents/*.ts
      timeout: 120_000,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    return out;
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string };
    return err.stdout || err.stderr || String(e);
  }
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", `http://${req.headers.host}`);
  const path = url.pathname;

  // Health check for probes / the marketplace.
  if (path === "/healthz") {
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true, merchant: WALLET, priceU: "0.1" }));
    return;
  }

  const m = path.match(/^\/v1\/agents\/(health|yield|lp|grid)$/);
  if (!m) {
    res.writeHead(404, { "content-type": "application/json" });
    res.end(JSON.stringify({ error: "not found" }));
    return;
  }
  const kind = m[1];

  // x402 guard: 402 + challenge on first contact, settle + serve when paid.
  const paymentHeader = req.headers["x-payment"] as string | undefined;
  const guardResult = await merchant.requirePayment(paymentHeader ?? null);
  if (guardResult.status === 402) {
    res.writeHead(402, { "content-type": "application/json" });
    res.end(JSON.stringify(guardResult.body));
    return;
  }

  const receipt = guardResult.receipt!;
  const report = await agentReport(kind);
  const body = {
    agent: kind,
    listing: `GuardRail ${kind} agent`,
    paid: {
      payer: receipt.payer,
      amount: receipt.amount.toString(),
      token: receipt.token,
      rail: receipt.rail,
    },
    report,
  };
  res.writeHead(200, { "content-type": "application/json" });
  res.end(JSON.stringify(body, null, 2));
});

server.listen(PORT, () => {
  console.log(`GuardRail x402 merchant listening on :${PORT}`);
  console.log(`payTo ${WALLET}, price 0.1 $U per report`);
  console.log(`endpoints: /v1/agents/{health|yield|lp|grid}`);
});
